project:
  type: website
  output-dir: docs

website:
  favicon: Assets/Images/byui_logo.png
  navbar:
    background: primary
    logo: Assets/Images/byui_logo.png
    left:
      - text: "Home"
        href: index.html

      - text: "Course Modules"
        menu:
          - text: "Module 1"
            href: modules/module1.html
          - text: "Module 2"
            href: modules/module2.html
          - text: "Module 3"
            href: modules/module3.html
          - text: "Module 4"
            href: modules/module4.html
          - text: "Module 5"
            href: modules/module5.html
          - text: "Module 6"
            href: modules/module6.html
          - text: "Module 7"
            href: modules/module7.html
          - text: "Module 8"
            href: modules/module8.html
          - text: "Module 9"
            href: modules/module9.html
          - text: "Module 10"
            href: modules/module10.html
          - text: "Module 11"
            href: modules/module11.html
          - text: "Module 12"
            href: modules/module12.html

      - text: "Dictionary"
        href: dictionary.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc-depth: 2
